name: ELD

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: jcs090218/setup-emacs@master
      with:
        version: 29.1

    - uses: emacs-eask/setup-eask@master
      with:
        version: 'snapshot'

    - uses: actions/checkout@v4

    - name: Generate elpa-packages.eld file
      run: make generate_eld

    - name: Set git config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Commit generated elpa-packages.eld
      continue-on-error: true
      run: |
        git pull --rebase --autostash
        git add .
        git commit -m "Update elpa-packages.eld"

    - name: Push updated data
      continue-on-error: true
      uses: jcs090218/github-push-action@master
      with:
        branch: master
        rebase: true
        retry: 3
